environment:
  ELECTRON_RUN_AS_NODE: 1
  VSCODE_BUILD_VERBOSE: true
install:
  - npm install

build_script:
  - npm run vscode:prepublish

test_script:
  - node --version
  - npm --version
  - npm test
